class TableNames:
    GENRE = 'genre'
    STYLE = 'style'
    THEME = 'theme'
    MOOD = 'mood'
    REVIEW_BODY = 'review_body'
    LABEL = 'label'
    ARTIST = 'artist'
    ALBUM = 'album'
    ROLE = 'role'
    CREDIT = 'credit'
    TRACK = 'track'
    COMPOSER_TRACK = 'composer_track'
    THEME_ALBUM = 'theme_album'
    STYLE_ALBUM = 'style_album'
    ARTIST_ALBUM = 'artist_album'
    MOOD_ALBUM = 'mood_album'
    REVIEW = 'review'
